name: continuous integration front

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_USERNAME: ${{ secrets.REMOTE_USERNAME }}
  REMOTE_KEY: ${{ secrets.REMOTE_KEY }}
  REMOTE_PORT: 22

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Npm install
        run: npm ci

      - name: Run prettier
        run: npx prettier --check .

      - name: build
        run: npm run build --if-present

      - name: Try to build docker image
        run: |
          sh build.sh

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}

      - name: publish
        run: |
          sh publish.sh

      - name: Restart apps in remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{env.REMOTE_HOST}}
          username: ${{env.REMOTE_USERNAME}}
          port: ${{env.REMOTE_PORT}}
          key: ${{env.REMOTE_KEY}}
          script: |
            sh start.sh

      