name: continuous integration front


on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Npm install
        run: npm install

      - name: Run prettier
        run: npx prettier --check .

      - name: build
        run: npm run build